on: [push]
name: Deploy Bicep template
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Getting started
        run: |
          echo Hello from GitHub Actions
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az group create --name Bicep --location eastus
            az deployment group what-if --name BicepDeployment --resource-group Bicep --template-file ./main.bicep
            az deployment group create --name BicepDeployment --resource-group Bicep --template-file ./main.bicep
